[package]
name = "iso_test"
version = "0.1.0"
authors = ["Jared Boone <jboone@earfeast.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3.0"
